//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.FileServer
{
    public class SaveBinaryFileRequest : Message
    {
        public const string RosMessageName = "file_server/SaveBinaryFile";

        public string name;
        public byte[] value;

        public SaveBinaryFileRequest()
        {
            this.name = "";
            this.value = new byte[0];
        }

        public SaveBinaryFileRequest(string name, byte[] value)
        {
            this.name = name;
            this.value = value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            
            listOfSerializations.Add(BitConverter.GetBytes(value.Length));
            listOfSerializations.Add(this.value);

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            
            var valueArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.value= new byte[valueArrayLength];
            for(var i = 0; i < valueArrayLength; i++)
            {
                this.value[i] = data[offset];
                offset += 1;
            }

            return offset;
        }

    }
}
